Aschlegle/issue295
telabotanica/naturadapt pull request #308
Opened 2021-11-02 09:52 UTC by aschlegle

Fixes #295
Ajout de la barre de recherche du header

2021-11-04 13:21 UTC, kstefanini requested changes
A priori, à part le href c'est nickel !

2021-11-04 13:21 UTC, kstefanini commented on templates/layout/header.html.twig
> +			<li class="toggle-search-link"><a href="">Rechercher</a></li>
Je ne suis pas fan des href vides, ce n'est pas sémantique ni valide, peux-tu utiliser un button ici à la place ?
Genre :
`<button type='button'>Rechercher</button>`

2021-11-04 14:02 UTC, Spone commented on templates/layout/header.html.twig
> +			<li class="toggle-search-link"><a href="">Rechercher</a></li>
Pour le moment il n'y a pas de href car la page n'existe pas (ça arrive dans #297). Je suis pour laisser un lien en mettant comme href `#TODO`

```suggestion
			<li class="toggle-search-link"><a href="#TODO">Rechercher</a></li>
```

2021-11-05 08:16 UTC, kstefanini commented on templates/layout/header.html.twig
> +			<li class="toggle-search-link"><a href="">Rechercher</a></li>
Ah oui, my bad !

2021-11-05 09:18 UTC, kstefanini approved these changes
👍

2021-11-05 09:37 UTC, Spone approved these changes

2021-11-22 08:56 UTC, merged