Traductions sur la page de recherche globale #322
telabotanica/naturadapt pull request #325
Opened 2022-01-20 11:33 UTC by aschlegle

2022-01-20 16:00 UTC, kstefanini approved these changes
:+1:

2022-01-26 09:16 UTC, Spone requested changes

2022-01-26 09:16 UTC, Spone commented on translations/messages.fr.yml
> +        membre: "MEMBRE"
```suggestion
        page: "Page"
        articles: "Actualité"
        discussion: "Discussion"
        document: "Document"
        membre: "Membre"
```

C'est mieux d'utiliser ensuite CSS pour les passer en majuscules (avec `text-transform: uppercase`)

2022-01-26 11:13 UTC, aschlegle commented on translations/messages.fr.yml
> +        membre: "MEMBRE"
Ok je  change ça

2022-01-26 11:17 UTC, Spone approved these changes

2022-01-26 11:39 UTC, merged